# Generated by Django 5.0.4 on 2024-04-05 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_password_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubName', models.CharField(max_length=80)),
                ('clubDescription', models.TextField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='userID',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=80)),
                ('timeStart', models.DateTimeField()),
                ('timeEnd', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('reoccurring', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.club')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending', models.BooleanField(default=False)),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.event')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserClubRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMember', models.BooleanField(default=False)),
                ('isManager', models.BooleanField(default=False)),
                ('clubID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.club')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
