# Generated by Django 5.0.4 on 2024-04-05 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passWord',
            new_name='password',
        ),
    ]
