# Generated by Django 5.0.4 on 2024-04-05 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_club_remove_user_userid_user_id_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isManager',
        ),
    ]
