# Generated by Django 5.0.4 on 2024-04-15 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_user_ismanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='email@email.com', max_length=80),
        ),
        migrations.AlterField(
            model_name='userclubrelation',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='app.user'),
        ),
    ]
